name: Node JS pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  SourceAnalysis:
    runs-on: ubuntu-latest
    steps:
      # Source Stage
      - name: Checkout
        uses: actions/checkout@v4
