name: Python & Docker pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Quality
        uses: Jasviers/actions/source-analysis/quality-checks@v1
        with:
          language: python

      - name: Build Docker Image
        uses: Jasviers/actions/build/docker-build@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Compliance
        uses: Jasviers/actions/source-analysis/compliance-checks@v1

      - name: Check Security
        uses: Jasviers/actions/source-analysis/security-checks@v1
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}

      - name: Run Unit Tests
        uses: Jasviers/actions/make-test/python-unit-test@v1

      - name: Generate Documentation
        uses: Jasviers/actions/make-docs/python-docs@v1
